[phases.setup]
nixPkgs = ["nodejs_24", "openssl"]

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npx prisma generate", "npx prisma db push --skip-generate", "npm run build"]
